### ISSUE TITLE
`invalid type` error occurred when attempting to set the temperature

### ISSUE THREAD

**Issue by XOKP** [rikhuijzer/ata#11]
> message: "invalid type: floating point `0.5`, expected i64"

It appears that setting a floating point temperature, such as 0.5 or 0.8, is not possible.

**Comment by rikhuijzer** [comment]
Thank you for opening an issue. Definitely a bug yes. Fixed in [v1.0.2](https://github.com/rikhuijzer/ata/releases/tag/v1.0.2).
