### ISSUE TITLE
Current release for aarch64 on macOS has the wrong cpu type 

### ISSUE THREAD

**Issue by mi-skam** [rikhuijzer/ata#13]
Hi,

I downloaded `ata-aarch64-apple-darwin` and tried to run it in the Terminal and got `-bash: /Users/plumps/Downloads/ata-aarch64-apple-darwin: Bad CPU type in executable` as response.

Checking the file type with file, showed that:
```
file ~/Downloads/ata-aarch64-apple-darwin 
/Users/plumps/Downloads/ata-aarch64-apple-darwin: Mach-O 64-bit executable **x86_64**
```

**Comment by rikhuijzer** [comment]
Thanks for reporting this. I was naively hoping that it would work to compile aarch64 from a x86 system. It looks like I should either compile aarch64 from inside QEMU or use runners from somewhere else such as buildjet.com (https://github.com/actions/runner-images/issues/5631).

I'll think about a solution to this and leave the issue open for now. I think you should be able to run the `ata-x86_64-unknown-linux-gnu` binaries via Rosetta or build aarm64 yourself via Cargo. Let me know if any of these options are not working

**Comment by rikhuijzer** [comment]
Haha great :smiley:
