### ISSUE TITLE
Got an error

### ISSUE THREAD

**Issue by Code-shaker** [rikhuijzer/ata#34]
``
Error:  
{
    "error": {
        "message": "You exceeded your current quota, please check your plan and billing details.",
        "type": "insufficient_quota",
        "param": null,
        "code": "insufficient_quota"
    }
}
``
So I didn't know what to do, need some help.

**Comment by rikhuijzer** [comment]
You probably need to add payment details to https://platform.openai.com/account/billing/overview.
