### ISSUE TITLE
I can only receive the following error when I ask any question.

### ISSUE THREAD

**Issue by loshlee** [rikhuijzer/ata#63]
I can only receive the following error when I ask any question. I never receive any other response. How can I fix it?

`Error:  
Response didn't contain 'data': {
    "error": {
        "message": "You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.",
        "type": "insufficient_quota",
        "param": null,
        "code": "insufficient_quota"
    }
}`

**Comment by rikhuijzer** [comment]
Well it already says what you should do: "You exceeded your current quota, please check your plan and billing details". You probably did not set up your credit card.

**Comment by loshlee** [comment]
Thanks. I don't really understand what I read when it comes to command lines use. Sometimes I'm lucky, but not this time.

**Comment by rikhuijzer** [comment]
Yeah I get that. No problem

**Comment by loshlee** [comment]
I signed up. I'm still looking into what the lowest cost option will be. I am a senior citizen, and I asked support at the OpenAI website for the lowest cost option. I've received what appears to be an elaborate answer, which I haven't yet digested, so time will tell. Anyway, for now at least, I don't receive an error when asking a question through either ata or llm. Thanks again.
